name: Import Issues
on:
  push:
    branches: [sarod/import-issues-from-mattermost]

permissions: 
    issues: write
jobs:
  import-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import Issues
        uses: dsanchezcr/issue-importer-action@v1.0.0
        with:
          file-path: import-issues/issues.csv
          file-format: csv
          github-token: ${{ secrets.GITHUB_TOKEN }}