name: Code Check
on:
  pull_request:

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-lint:
    name: Run ruff
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - uses: astral-sh/ruff-action@v3

      - name: Display current path
        run: |
          echo $pwd

      - run: ruff format $GITHUB_WORKSPACE/opi-api

      - run: ruff check --fix $GITHUB_WORKSPACE/opi-api
